medical/api/urls.py
from django.conf.urls import include, patterns, url
from rest_framework_extensions.routers import ExtendedDefaultRouter, ExtendedSimpleRouter
from api import utils
from .views import InstitutionViewSet, CommentsViewSet, CategoryViewSet, DoctorsViewSet, PhotoViewSet, PhoneViewSet, \
    ActionViewSet, PriceViewSet, ServiceViewSet, SpecialtyViewSet, PushUplistViewSet, BannerViewSet

router = ExtendedSimpleRouter()
router.register(r'categories', CategoryViewSet, 'category')
# router.register(r'doctor', DoctorsViewSet, 'doctor')
router.register(r'doctor', DoctorsViewSet, 'doctor')
router.register(r'services', ServiceViewSet, 'service')
router.register(r'institution', InstitutionViewSet, 'institution')\
     .register(r'phones', PhoneViewSet, 'phones', parents_query_lookups=['rel_institution'])
router.register(r'comments', CommentsViewSet, 'comment')
router.register(r'institution', InstitutionViewSet, 'institution')\
       .register(r'comments', CommentsViewSet, 'comment', parents_query_lookups=['institution__pk'])
router.register(r'actions', ActionViewSet, 'action')
router.register(r'institution', InstitutionViewSet, 'institution')

router.register(r'institution', InstitutionViewSet, 'institution')
router.register(r'price', PriceViewSet, 'price')
router.register(r'comments', CommentsViewSet, 'parent-comments')
router.register(r'specialty', SpecialtyViewSet, 'specialty')
router.register(r'push', PushUplistViewSet, 'push')
router.register(r'banners', BannerViewSet, 'banner')

urlpatterns = patterns(
     '',
     url(r'^', include(router.urls)),
     url(r'^actions_count/$', utils.actions_count, name='actions_count'),
)

medical/base/urls.py
"""urlconf for the base application"""

from django.conf.urls import patterns, include, url
from django.conf import settings


urlpatterns = patterns('base.views',
                       url(r'^$', 'login', name='login'),
                       url(r'^home/$', 'home', name='home'),
                       url(r'^auth/$', 'auth_view', name='auth_view'),
                       url(r'^logout/$', 'logout', name='logout'),
                       url(r'^logged_in/$', 'logged_in', name='logged_in'),
                       url(r'^institution_create/$', 'institution_create', name='institution_create'),
                       url(r'^category_create/$', 'category_create', name='category_create'),
                       url(r'^comment_create/$', 'comment_create', name='comment_create'),
                       url(r'^institutions_list/$', 'institutions_list', name='institutions_list'),
                       url(r'^categories_list/$', 'categories_list', name='categories_list'),
                       url(r'^comments_list/$', 'comments_list', name='comments_list'),
                       url(r'^institution_update/(?P<institution_id>\d+)/$', 'institution_update',
                           name='institution_update'),
                       url(r'^institution_delete/(?P<institution_id>\d+)/$', 'institution_delete',
                           name='institution_delete'),
                       url(r'^category_update/(?P<category_id>\d+)/', 'category_update', name='category_update'),
                       url(r'^category_delete/(?P<category_id>\d+)/', 'category_delete', name='category_delete'),
                       url(r'^comment_update/(?P<comment_id>\d+)/', 'comment_update', name='comment_update'),
                       url(r'^comment_delete/(?P<comment_id>\d+)/', 'comment_delete', name='comment_delete'),
                       url(r'^feedback/$', 'feedback', name='feedback'),
                       url(r'^feedback-list', 'feedback_list', name='feedback_list'),
                       url(r'^feedback-delete/(?P<id>\d+)/$', 'feedback_delete', name='feedback_delete'),
                       url(r'^about-project', 'about_project', name='about_project'),
                       url(r'^information-create', 'information_create', name='information_create'),
                       url(r'^information-update/(?P<id>\d+)/$', 'information_update', name='information_update'),
                       url(r'^contacts', 'contacts', name='contacts'),
                       url(r'^contact-create', 'contact_create', name='contact_create'),
                       url(r'^contact-delete/(?P<id>\d+)/$', 'contact_delete', name='contact_delete'),
                       url(r'^contact-update/(?P<id>\d+)/$', 'contact_update', name='contact_update'),
                       url(r'^actions', 'actions', name='actions'),
                       url(r'^action-create', 'action_create', name='action_create'),
                       url(r'^action-delete/(?P<id>\d+)/$', 'action_delete', name='action_delete'),
                       url(r'^action-update/(?P<id>\d+)/$', 'action_update', name='action_update'),
                       url(r'^upload/(?P<ggwp>\d+)/$', 'import_data', name='import_data'),
                       url(r'^search-form/$', 'search_form', name='search_form'),
                       url(r'^search/$', 'search', name='search'),

                       url(r'^institutions/$', 'institutions', name='institutions'),
                       url(r'^comments/$', 'comments', name='comments'),
                       url(r'^services/$', 'services', name='services'),
                       url(r'^acttions-list/$', 'acttions_list', name='acttions_list'),
                       url(r'^institution_updat/(?P<institution_id>\d+)/$', 'institution_updat',
                           name='institution_updat'),
                       url(r'^action_upd/(?P<id>\d+)/$', 'action_upd', name='action_upd'),
                       url(r'^upd_comment/(?P<id>\d+)/$', 'upd_comment', name='upd_comment'),
                       url(r'^service_upd/(?P<id>\d+)/$', 'service_upd', name='service_upd'),

                       url(r'^doctor-list/$', 'doctor_list', name='doctor_list'),
                       url(r'^doctor-create/$', 'doctor_create', name='doctor_create'),
                       url(r'^doctor-update/(?P<id>\d+)/$', 'doctor_update', name='doctor_update'),
                       url(r'^doctor-delete/(?P<id>\d+)/$', 'doctor_delete', name='doctor_delete'),

                       url(r'^specialty-list/$', 'specialty_list', name='specialty_list'),
                       url(r'^specialty-create/$', 'specialty_create', name='specialty_create'),
                       url(r'^specialty-update/(?P<id>\d+)/$', 'specialty_update', name='specialty_update'),
                       url(r'^specialty-delete/(?P<id>\d+)/$', 'specialty_delete', name='specialty_delete'),

                       url(r'^banner-list/$', 'banner_list', name='banner_list'),
                       url(r'^banner-create/$', 'banner_create', name='banner_create'),
                       url(r'^banner-update/(?P<id>\d+)/$', 'banner_update', name='banner_update'),
                       url(r'^banner-delete/(?P<id>\d+)/$', 'banner_delete', name='banner_delete'),
)

medical/medical/urls.py
""" Default urlconf for medical """
import settings.base as settings
from django.conf.urls import include, patterns, url
from django.contrib.auth.views import logout
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
admin.autodiscover()


def bad(request):
    """ Simulates a server error """
    1 / 0


urlpatterns = i18n_patterns(
    '',
    url(r'', include('base.urls', namespace='base')),
    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^bad/$', bad),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += patterns(url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                                {'document_root': settings.MEDIA_ROOT}),)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

medical/base/models.py
""" Basic models, such as user profile """

medical/templates/base/categories.html
{% extends "_layouts/base.html" %}
{% load i18n %}
{% block css %}
    {{ block.super }}
    <style>
        /* Move down content because we have a fixed navbar that is 50px tall */
        body {
            padding-top: 80px;
            padding-bottom: 20px;
            color: #888;
        }

        td:last-child {
            text-align: right;
        }
    </style>
{% endblock css %}

{% block page_title %}Your Site - Home{% endblock %}
{% block page_class %}home-page{% endblock %}
{% block content %}

    <div class="container">
        <div class="row">
            <h2>{% trans 'Категории' %} <a href="{% url 'base:category_create' %}" class="btn btn-success"><i
                    class="fa fa-plus"></i>
                {% trans 'Добавить' %}</a></h2>
            <br/>

            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>№</th>
                            <th>{% trans 'Название' %}</th>
                            <th>{% trans 'Лого' %}</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for category in categories %}
                            <tr>
                                <td>{{ category.id }}</td>
                                <td>{{ category.title }}</td>
                                <td>{{ category.logo }}</td>
                                <td>
                                    <a href="{% url 'base:category_update' category.id %}"
                                       class="btn btn-primary edit"><i class="fa fa-pencil"></i>{% trans 'Изменить' %}</a>
                                    <a href="{% url 'base:category_delete' category.pk %}"
                                       class="btn btn-danger delete"><i class="fa fa-trash-o"></i>{% trans 'Удалить' %}</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

medical/templates/base/comments.html
{% extends "_layouts/base.html" %}
{% load i18n %}
{% block css %}
    {{ block.super }}
    <style>
        /* Move down content because we have a fixed navbar that is 50px tall */
        body {
            padding-top: 80px;
            padding-bottom: 20px;
            color: #888;
        }

        td:last-child {
            text-align: right;
        }
    </style>
{% endblock css %}

{% block page_title %}Your Site - Home{% endblock %}
{% block page_class %}home-page{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <h2>{% trans 'Комментарии' %} <a href="{% url 'base:comment_create' %}" class="btn btn-success"><i
                    class="fa fa-plus"></i>
                {% trans 'Добавить' %}</a></h2>
            <br/>

            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>№</th>
                            <th>{% trans 'Заведение' %}</th>
                            <th>{% trans 'Комментатор' %}</th>
                            <th>{% trans 'Комментарий' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for comment in comments %}
                            <tr>
                                <td>{{ comment.id }}</td>
                                <td>{{ comment.institution }}</td>
                                <td>{{ comment.commentator_name }}</td>
                                <td>{{ comment.comment|safe }}</td>
                                <td>
                                    <a href="{% url 'base:comment_update' comment.id %}"
                                       class="btn btn-primary edit"><i class="fa fa-pencil"></i>{% trans 'Изменить' %}</a>
                                    <a href="{% url 'base:comment_delete' comment.id %}"
                                       class="btn btn-danger delete"><i class="fa fa-trash-o"></i>{% trans 'Удалить' %}</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

medical/templates/base/doctor_list.html
{% extends "_layouts/base.html" %}
{% load i18n %}
{% block css %}
    {{ block.super }}
    <style>
        /* Move down content because we have a fixed navbar that is 50px tall */
        body {
            padding-top: 80px;
            padding-bottom: 20px;
            color: #888;
        }

        td:last-child {
            text-align: right;
        }
    </style>
{% endblock css %}

{% block page_title %}Your Site - Home{% endblock %}
{% block page_class %}home-page{% endblock %}
{% block content %}

    <div class="container">
        <div class="row">
            <h2>{% trans 'Врачи' %}</h2>
            <br/>
            <a href="{% url 'base:doctor_create' %}" class="btn btn-success"><i
                    class="fa fa-plus"></i>
                {% trans 'Добавить' %}</a>

            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>№</th>
                            <th>{% trans 'Категория' %}</th>
                            <th>{% trans 'Заведение' %}</th>
                            <th>{% trans 'Имя' %}</th>
                            <th>{% trans 'Телефон' %}</th>
                            <th>{% trans 'Почта' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for doctor in doctors %}
                            <tr>
                                <td>{{ doctor.id }}</td>
                                <td>{{ doctor.speciality }}</td>
                                <td>{{ doctor.rel_institution }}</td>
                                <td>{{ doctor.name }}</td>
                                <td>{{ doctor.phone_number }}</td>
                                <td>{{ doctor.email }}</td>
                                <td>
                                    <a href="{% url 'base:doctor_update' doctor.id %}"
                                       class="btn btn-primary edit"><i class="fa fa-pencil"></i>{% trans 'Изменить' %}
                                    </a>
                                    <a href="{% url 'base:doctor_delete' doctor.id %}"
                                       class="btn btn-danger delete"><i class="fa fa-trash-o"></i>{% trans 'Удалить' %}
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                        <div class="pagination">
                            <span class="step-links">
                                {% if doctors.has_previous %}
                                    <a href="?page={{ doctors.previous_page_number }}">previous</a>
                                {% endif %}

                                <span class="current">
                                    Page {{ doctors.number }} of {{ doctors.paginator.num_pages }}.
                                </span>

                                {% if doctors.has_next %}
                                    <a href="?page={{ doctors.next_page_number }}">next</a>
                                {% endif %}
                            </span>
                        </div>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

medical/templates/base/home.html
{% extends "_layouts/base.html" %}
{% load i18n %}
{% load l10n %}
{% block css %}
    {{ block.super }}
    <style>
        /* Move down content because we have a fixed navbar that is 50px tall */
        body {
            padding-top: 50px;
            padding-bottom: 20px;
        }

        .fa {
            margin-right: 10px;
        }

        th {
            font-size: large;
        }

        .breakage {
            margin-right: 15px;
        }
    </style>
{% endblock css %}

{% block page_title %}Your Site - Home{% endblock %}
{% block page_class %}home-page{% endblock %}
{% block content %}
    {% if user.is_superuser %}
    <div class="jumbotron">
        <div class="container">
            <h1>{% trans 'Административная панель' %}</h1>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <table class="table table-responsive">
                <tbody>
                <tr>
                    <th class="col-xs-8"><a href="{% url 'base:categories_list' %}">{% trans 'Категории' %}</a></th>
                    <td class="col-xs-4 text-right"><a href="{% url 'base:category_create' %}"
                                                       class="btn btn-success"><i
                            class="fa fa-plus"></i>
                        {% trans 'Добавить' %}</a><span class="breakage"></span><a href="{% url 'base:categories_list' %}"
                                                                     class="btn btn-primary"><i
                            class="fa fa-pencil"></i>{% trans 'Изменить' %}</a></td>
                </tr>
                <tr>
                    <th class="col-xs-8"><a href="{% url 'base:specialty_list' %}">{% trans 'Специальности' %}</a></th>
                    <td class="col-xs-4 text-right"><a href="{% url 'base:specialty_create' %}" class="btn btn-success"><i
                            class="fa fa-plus"></i>
                        {% trans 'Добавить' %}</a><span class="breakage"></span><a href="{% url 'base:specialty_list' %}"
                                                                     class="btn btn-primary"><i
                            class="fa fa-pencil"></i>{% trans 'Изменить' %}</a></td>
                </tr>

                <tr>
                    <th class="col-xs-8"><a href="{% url 'base:institutions_list' %}">{% trans 'Заведения' %}</a></th>
                    <td class="col-xs-4 text-right"><a href="{% url 'base:institution_create' %}"
                                                       class="btn btn-success"><i
                            class="fa fa-plus"></i>
                        {% trans 'Добавить' %}</a><span class="breakage"></span><a href="{% url 'base:institutions_list' %}"
                                                                     class="btn btn-primary"><i
                            class="fa fa-pencil"></i>{% trans 'Изменить' %}</a></td>
                </tr>
                <tr>
                    <th class="col-xs-8"><a href="{% url 'base:doctor_list' %}">{% trans 'Врачи' %}</a></th>
                    <td class="col-xs-4 text-right"><a href="{% url 'base:doctor_create' %}" class="btn btn-success"><i
                            class="fa fa-plus"></i>
                        {% trans 'Добавить' %}</a><span class="breakage"></span><a href="{% url 'base:comments_list' %}"
                                                                     class="btn btn-primary"><i
                            class="fa fa-pencil"></i>{% trans 'Изменить' %}</a></td>
                </tr>

                <tr>
                    <th class="col-xs-8"><a href="{% url 'base:comments_list' %}">{% trans 'Комментарии' %}</a></th>
                    <td class="col-xs-4 text-right"><a href="{% url 'base:comment_create' %}" class="btn btn-success"><i
                            class="fa fa-plus"></i>
                        {% trans 'Добавить' %}</a><span class="breakage"></span><a href="{% url 'base:comments_list' %}"
                                                                     class="btn btn-primary"><i
                            class="fa fa-pencil"></i>{% trans 'Изменить' %}</a></td>
                </tr>


                <tr>
                    <th class="col-xs-8"><a href="{% url 'base:contacts' %}">{% trans 'Контакты' %}</a></th>
                    <td class="col-xs-4 text-right"><a href="{% url 'base:contact_create' %}" class="btn btn-success"><i
                            class="fa fa-plus"></i>
                        {% trans 'Добавить' %}</a><span class="breakage"></span><a href="{% url 'base:contacts'%}"
                                                                     class="btn btn-primary"><i
                            class="fa fa-pencil"></i>{% trans 'Изменить' %}</a></td>
                </tr>


                <tr>
                    <th class="col-xs-8"><a href="{% url 'base:about_project' %}">{% trans 'Информация о проекте' %}</a></th>
                    <td class="col-xs-4 text-right"><a href="{% url 'base:information_create' %}" class="btn btn-success"><i
                            class="fa fa-plus"></i>
                        {% trans 'Добавить' %}</a><span class="breakage"></span><a href="{% url 'base:about_project'%}"
                                                                     class="btn btn-primary"><i
                            class="fa fa-pencil"></i>{% trans 'Изменить' %}</a></td>
                </tr>

                <tr>
                    <th class="col-xs-8"><a href="{% url 'base:actions' %}">{% trans 'Акции' %}</a></th>
                    <td class="col-xs-4 text-right"><a href="{% url 'base:action_create' %}" class="btn btn-success"><i
                            class="fa fa-plus"></i>
                        {% trans 'Добавить' %}</a><span class="breakage"></span><a href="{% url 'base:actions'%}"
                                                                     class="btn btn-primary"><i
                            class="fa fa-pencil"></i>{% trans 'Изменить' %}</a></td>
                </tr>

                <tr>
                    <th class="col-xs-8"><a href="{% url 'base:feedback_list' %}">{% trans 'Обратная связь' %}</a></th>
                </tr>


                    <tr>
                        <th class="col-xs-8"><a href="{% url 'base:banner_list' %}">{% trans 'Баннер' %}</a></th>
                        <td class="col-xs-4 text-right"><a href="{% url 'base:banner_create' %}"
                                                           class="btn btn-success"><i
                                class="fa fa-plus"></i>
                            {% trans 'Добавить' %}</a><span class="breakage"></span><a href="{% url 'base:banner_list' %}"
                                                                                       class="btn btn-primary"><i
                                class="fa fa-pencil"></i>{% trans 'Изменить' %}</a></td>
                    </tr>

                </tbody>
            </table>
        </div>
    </div>
{% else %}
    <div class="jumbotron">
        <div class="container">
            <h1>{% trans 'Административная панель' %}</h1>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <table class="table table-responsive">
                <tbody>
                <tr>
                    <th class="col-xs-8"><a href="{% url 'base:institutions' %}">{% trans 'Заведения' %}</a></th>
                    <td class="col-xs-4 text-right"><span class="breakage"></span><a href="{% url 'base:institutions' %}"
                                                                     class="btn btn-primary"><i
                            class="fa fa-pencil"></i>{% trans 'Изменить' %}</a></td>
                </tr>
                <tr>
                    <th class="col-xs-8"><a href="{% url 'base:comments' %}">{% trans 'Комментарии' %}</a></th>
                    <td class="col-xs-4 text-right"><span class="breakage"></span><a href="{% url 'base:comments' %}"
                                                                     class="btn btn-primary"><i
                            class="fa fa-pencil"></i>{% trans 'Изменить' %}</a></td>
                </tr>
                <tr>
                    <th class="col-xs-8"><a href="{% url 'base:services' %}">{% trans 'Услуги' %}</a></th>
                    <td class="col-xs-4 text-right"><span class="breakage"></span><a href="{% url 'base:services' %}"
                                                                     class="btn btn-primary"><i
                            class="fa fa-pencil"></i>{% trans 'Изменить' %}</a></td>
                </tr>
                <tr>
                    <th class="col-xs-8"><a href="{% url 'base:acttions_list' %}">{% trans 'Акции' %}</a></th>
                    <td class="col-xs-4 text-right"><span class="breakage"></span><a href="{% url 'base:acttions_list' %}"
                                                                     class="btn btn-primary"><i
                            class="fa fa-pencil"></i>{% trans 'Изменить' %}</a></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endif %}
{% endblock %}

medical/templates/base/institutions.html
{% extends "_layouts/base.html" %}
{% load i18n %}
{% block css %}
    {{ block.super }}
    <style>
        /* Move down content because we have a fixed navbar that is 50px tall */
        body {
            padding-top: 80px;
            padding-bottom: 20px;
            color: #888;
        }

        td:last-child {
            text-align: right;
        }
    </style>
{% endblock css %}

{% block page_title %}Your Site - Home{% endblock %}
{% block page_class %}home-page{% endblock %}
{% block content %}

    <div class="container">
        <div class="pagination">
            <span class="step-links">
                {% if institutions.has_previous %}
                    <a href="?page={{ institutions.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ institutions.number }} of {{ institutions.paginator.num_pages }}.
                </span>

                {% if institutions.has_next %}
                    <a href="?page={{ institutions.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
        <div class="row">
            <h2>{% trans 'Заведения' %} <a href="{% url 'base:institution_create' %}" class="btn btn-success"><i
                    class="fa fa-plus"></i>
                {% trans 'Добавить' %}</a></h2>
            <br/>

            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>№</th>
                            <th>{% trans 'Имя' %}</th>
                            <th>{% trans 'Категория' %}</th>
                            <th>{% trans 'Описание' %}</th>
                            <th>{% trans 'Почта' %}</th>
                            <th>{% trans 'Адрес' %}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for institution in institutions %}
                            <tr>
                                <td>{{ institution.id }}</td>
                                <td>{{ institution.name }}</td>
                                <td>
                                    {% for category in institution.category.all %}
                                        {{category}}
                                    {% endfor %}
                                </td>
                                <td>{{ institution.short_description|safe }}</td>
                                <td>{{ institution.email }}</td>
                                <td>{{ institution.address }}</td>
                                <td>
                                    <a href="{% url 'base:institution_update' institution.id %}"
                                       class="btn btn-primary edit"><i class="fa fa-pencil"></i>{% trans 'Изменить' %}</a>
                                    <a href="{% url 'base:institution_delete' institution.id %}"
                                       class="btn btn-danger delete"><i class="fa fa-trash-o"></i>{% trans 'Удалить' %}</a>
                                </td>
                            </tr>
                        {% endfor %}

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

medical/templates/base/services_list.html
{% extends "_layouts/base.html" %}
{% load i18n %}
{% block css %}
    {{ block.super }}
    <style>
        /* Move down content because we have a fixed navbar that is 50px tall */
        body {
            padding-top: 80px;
            padding-bottom: 20px;
            color: #888;
        }

        td:last-child {
            text-align: right;
        }
    </style>
{% endblock css %}

{% block page_title %}Your Site - Home{% endblock %}
{% block page_class %}home-page{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <h2>{% trans 'Услуги' %}</h2>
            <br/>

            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>№</th>
                            <th>{% trans 'Название' %}</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for service in services %}
                            <tr>
                                <td>{{ service.id }}</td>
                                <td>{{ service.title }}</td>
                                <td>
                                    <a href="{% url 'base:service_upd' service.id %}"
                                       class="btn btn-primary edit"><i class="fa fa-pencil"></i>{% trans 'Изменить' %}</a>
{#                                    <a href="{% url 'base:action_delete' action.id %}"#}
{#                                       class="btn btn-danger delete"><i class="fa fa-trash-o"></i>{% trans 'Удалить' %}</a>#}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}